
server:
  port: 3000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kob?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
  #    protocol: smtps  ??163 ? smtps  qq?smtp
    protocol: smtps
    # ?? SMTP ?????
    host: smtp.163.com
    # ?????
    #    username:
    username: zzac0420@163.com
    # ??????????????????????????
    password: BXWPKCLJQILSAGPJ
    # ???465?587
    #    port: 465
    port: 465
    # ????????UTF-8
    default-encoding: UTF-8

    ############################################################
    # REDIS 配置
    ############################################################
  redis:
    database: 0           # Redis数据库索引（默认为0）
    host : 127.0.0.1      # Redis服务器地址
    password:             # Redis服务器连接密码（默认为空）
    port : 6379           # Redis服务器连接端口
    jedis:
      pool:
        max-active: 8     # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 2       # 连接池中的最小空闲连接
    connect-timeout: 6000 # 连接超时时间（毫秒）


